services:
  mysql:
    image: "mysql:8.4"
    container_name: eulabs-mysql
    restart: always
    environment:
      MYSQL_USER: "dev"
      MYSQL_PASSWORD: "5up3r53cr37"
      MYSQL_ROOT_PASSWORD: "5up3r53cr37r007"
      MYSQL_DATABASE: "eulabs"
    ports:
      - '8000:3306'
    volumes:
      - ./db-volume:/var/lib/mysql
      - ./deploy/migration:/docker-entrypoint-initdb.d
